branch-defaults:
  master:
    environment: anglerfish-production
    group_suffix: null
  staging:
    environment: anglerfish-staging
    group_suffix: null
global:
  application_name: anglerfish
  default_ec2_keyname: anglerfish-key
  default_platform: Node.js
  default_region: ap-northeast-1
  profile: null
  sc: git
