branch-defaults:
  master:
    environment: anglerfish-dev
    group_suffix: null
  staging:
    environment: anglerfish-staging
    group_suffix: null
global:
  application_name: anglerfish
  default_ec2_keyname: paas-study-kaneko
  default_platform: Node.js
  default_region: ap-northeast-1
  profile: null
  sc: git
